name: Sync Algorithm List

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JSON file
        run: |
          # UPDATE THIS PATH to wherever you want the JSON to live in c2pa-org.github.io
          mkdir -p sbal/softbinding-alg-list
          
          # Download the file directly from the source repository
          curl -s https://raw.githubusercontent.com/c2pa-org/softbinding-algorithm-list/refs/heads/main/softbinding-algorithm-list.json -o sbal/softbinding-alg-list/softbinding-algorithm-list.json

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # UPDATE THIS PATH to match the destination folder above
          git add sbal/softbinding-alg-list/softbinding-algorithm-list.json
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update softbinding algorithm list to latest" && git push)
